# docker-compose.yaml
services:
  administration-service:
    build: ./administration-service
    container_name: administration-service
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://myuser:mysecretpassword@db:5432/mydatabase"
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      # This line runs your migrations on startup
      - ./migrations:/docker-entrypoint-initdb.d
      
      # This line persists the database data
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: