# docker-compose.yaml
services:
  administration-service:
    build: ./administration-service
    container_name: administration-service
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://myuser:mysecretpassword@db:5432/mydatabase"
      AUTH_SERVICE_URL: "http://auth-service:8001"
    depends_on:
      - db
      - redis
      - auth-service
  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: always
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: "postgresql://myuser:mysecretpassword@db:5432/mydatabase"
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - db
      - redis
  communication-service:
    build: ./comunication
    container_name: communication-service
    restart: always
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: "postgresql://myuser:mysecretpassword@db:5432/mydatabase"
      AUTH_SERVICE_URL: "http://auth-service:8001"
    depends_on:
      - db
      - auth-service
  db:
    image: postgres:15
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      # This line runs your migrations on startup
      - ./migrations:/docker-entrypoint-initdb.d
      
      # This line persists the database data
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: local_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: